=== Amit2016-17/osgi/org.osgi.service.blueprint/src/org/osgi/service/blueprint/metadata/blueprint.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
    /*
    * $Revision$
    *
    * Copyright (c) OSGi Alliance (2008, 2009). All Rights Reserved.
    *
    * Licensed under the Apache License, Version 2.0 (the "License");
    * you may not use this file except in compliance with the License.
    * You may obtain a copy of the License at
    *
    *      http://www.apache.org/licenses/LICENSE-2.0
    *
    * Unless required by applicable law or agreed to in writing, software
    * distributed under the License is distributed on an "AS IS" BASIS,
    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    * See the License for the specific language governing permissions and
    * limitations under the License.
    */
    -->
<xsd:schema xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.osgi.org/xmlns/blueprint/v1.0.0"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            version="1.0.0">

    <!-- Schema elements for core component declarations -->

    <xsd:complexType name="Tidentified" abstract="true">
        <xsd:attribute name="id" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="blueprint" type="Tblueprint"/>

    <xsd:complexType name="Tblueprint">
        <xsd:sequence>
            <xsd:element name="description" type="Tdescription" minOccurs="0"/>
            <xsd:element name="type-converters" type="Ttype-converters" minOccurs="0" maxOccurs="1"/>
            <!-- top-level components -->
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:group ref="allComponents"/>
            </xsd:choice>
        </xsd:sequence>

        <!-- Defaults-->
        <xsd:attribute name="default-lazy-init" default="false"
            type="Tlazy-init"/>
        <xsd:attribute name="default-init-method" type="Tmethod"/>
        <xsd:attribute name="default-destroy-method" type="Tmethod"/>
        <xsd:attribute name="default-timeout" type="xsd:unsignedLong"
            default="300000"/>
        <xsd:attribute name="default-availability" type="Tavailability"
            default="mandatory"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <!--<xsd:element name="description" type="Tdescription"/>-->

    <xsd:complexType name="Tdescription" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded"/>
    </xsd:complexType>

    <!--<xsd:element name="type-converters" type="Ttype-converters"/>-->

    <xsd:complexType name="Ttype-converters">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:group ref="refOrTargetComponent"/>
        </xsd:choice>
    </xsd:complexType>

	<!-- Components that provide a reasonable target for injection
	used for listeners, etc. -->

	<xsd:group name="targetComponent">
		<xsd:choice>
			<xsd:element name="bean" type="Tbean"/>
			<xsd:element name="reference" type="Treference"/>
			<xsd:any namespace="##other" processContents="strict" minOccurs="0"
				maxOccurs="unbounded"/>
		</xsd:choice>
	</xsd:group>

	<xsd:group name="refOrTargetComponent">
		<xsd:choice>
            <xsd:element name="ref" type="Tref"/>
			<xsd:group ref="targetComponent"/>
		</xsd:choice>
	</xsd:group>

	<xsd:group name="allComponents">
		<xsd:choice>
			<xsd:element name="service" type="Tservice"/>
			<xsd:element name="ref-list" type="Tref-collection"/>
			<xsd:element name="ref-set" type="Tref-collection"/>
			<xsd:group ref="targetComponent"/>
		</xsd:choice>
	</xsd:group>

    <xsd:group name="beanElements">
        <xsd:sequence>
            <xsd:element name="description" type="Tdescription" minOccurs="0"/>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="argument" type="Targument"/>
                <xsd:element name="property" type="Tproperty"/>
                <xsd:any namespace="##other" processContents="strict" minOccurs="0"
                         maxOccurs="unbounded"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:group>

    <xsd:complexType name="Tbean">
        <xsd:complexContent>
            <xsd:extension base="Tidentified">
                <xsd:group ref="beanElements"/>
				<xsd:attribute name="class" type="Tclass"/>
				<xsd:attribute name="depends-on" type="xsd:normalizedString"/>
				<xsd:attribute name="init-method" type="Tmethod"/>
				<xsd:attribute name="destroy-method" type="Tmethod"/>
				<xsd:attribute name="factory-method" type="Tmethod"/>
				<xsd:attribute name="factory-component" type="Tidref"/>

				<xsd:attribute name="scope">
					<xsd:simpleType>
						<xsd:restriction base="xsd:NMTOKEN">
							<xsd:enumeration value="singleton"/>
							<xsd:enumeration value="prototype"/>
							<xsd:enumeration value="bundle"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>

				<xsd:attribute name="lazy-init" type="Tlazy-init" default="default"/>
                <xsd:anyAttribute namespace="##other" processContents="lax"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="Targument">
        <xsd:sequence>
            <xsd:element name="description" type="Tdescription" minOccurs="0"/>
            <xsd:group ref="value"/>
        </xsd:sequence>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger"/>
        <xsd:attribute name="type" type="Tclass"/>
        <xsd:attribute name="ref" type="Tidref"/>
        <xsd:attribute name="value" type="TstringValue"/>
    </xsd:complexType>

    <xsd:complexType name="Tproperty">
        <xsd:sequence>
            <xsd:element name="description" type="Tdescription" minOccurs="0"/>
            <xsd:group ref="value"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="Tmethod" use="required"/>
        <xsd:attribute name="ref" type="Tidref"/>
        <xsd:attribute name="value" type="TstringValue"/>
    </xsd:complexType>

    <!--<xsd:element name="ref" type="Tref"/>-->

    <xsd:complexType name="Tref">
        <xsd:complexContent>
            <xsd:restriction base="xsd:anyType">
                <xsd:attribute name="component" type="Tidref" use="required"/>
            </xsd:restriction>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="Tnull" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded"/>
    </xsd:complexType>

    <xsd:complexType name="Tkey">
        <xsd:group ref="nonNullValue"/>
    </xsd:complexType>

    <xsd:complexType name="Treference">
        <xsd:complexContent>
            <xsd:extension base="Tidentified">
                <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                    <xsd:element name="interfaces" type="TlistSetArray" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="listener" type="Tlistener" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
                <xsd:attribute name="interface" use="optional" type="xsd:token"/>
                <xsd:attribute name="filter" use="optional" type="xsd:string"/>
                <xsd:attribute name="component-name" type="xsd:string" use="optional"/>
                <xsd:attribute name="availability" use="optional" type="Tavailability" default="mandatory"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

	<!-- reference -->
	<xsd:complexType name="Treference">
		<xsd:complexContent>
			<xsd:extension base="TserviceReference">
				<xsd:attribute name="timeout" use="optional" type="xsd:unsignedLong"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- ref-set, ref-list -->
	<xsd:complexType name="Tref-collection">
		<xsd:complexContent>
			<xsd:extension base="TserviceReference">
                 <xsd:element name="comparator" type="Tcomparator" minOccurs="0" maxOccurrs="1"/>

				<xsd:attribute name="comparator-ref" type="xsd:token"
					use="optional"/>

				<xsd:attribute name="member-type" use="optional">
					<xsd:simpleType>
						<xsd:restriction base="xsd:NMTOKEN">
							<xsd:enumeration value="service-instance"/>
							<xsd:enumeration value="service-reference"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>

				<xsd:attribute name="ordering-basis" use="optional">
					<xsd:simpleType>
						<xsd:restriction base="xsd:NMTOKEN">
							<xsd:enumeration value="service"/>
							<xsd:enumeration value="service-reference"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>

			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Reference base class -->
	<xsd:complexType name="TserviceReference">
		<xsd:complexContent>
			<xsd:extension base="Tcomponent">
   				<xsd:element name="interfaces" minOccurs="0" maxOccurs="1"
   					type="Tinterfaces"/>

   				<!-- listener ### why is this called listerm and not reference listener? -->
   				<xsd:element name="listener" type="TReferenceListener" minOccurs="0"
   					maxOccurs="unbounded"/>

				<xsd:attribute name="interface" use="optional" type="Tclass"/>
				<xsd:attribute name="filter" use="optional" type="xsd:normalizedString"/>
				<xsd:attribute name="component-name" type="Tidref"
					use="optional"/>
				<xsd:attribute name="availability" type="Tavailability"
					use="optional" default="mandatory"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

    <xsd:complexType name="TReferencelistener">
        <xsd:group ref="refOrTargetComponent"/>
        <xsd:attribute name="ref" type="xsd:token"
            use="optional"/>
        <xsd:attribute name="bind-method" type="Tmethod"
            use="required"/>
        <xsd:attribute name="unbind-method" type="Tmethod"
            use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="Tlazy-init">
        <xsd:restriction base="xsd:NMTOKEN">
            <xsd:enumeration value="false"/>
            <xsd:enumeration value="true"/>
            <xsd:enumeration value="default"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Tavailability">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="mandatory"/>
            <xsd:enumeration value="optional"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="Tcomparator">
        <xsd:group ref="refOrTargetComponent"/>
    </xsd:complexType>

    <!-- service -->

    <xsd:complexType name="Tservice">
        <xsd:complexContent>
            <xsd:extension base="Tcomponent">
                <xsd:element name="interfaces" type="Tinterfaces"
                    minOccurs="0"/>

   				<!-- #### I'm not sure this should be a Tmap.  Service properties can only
                     have string keys, and Map can have any type.  I suspect this needs its
                     own type -->
                <xsd:element name="service-properties" type="Tmap"
                    minOccurs="0"/>
                <xsd:element name="registration-listener" type="TregistrationListener"
                    minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="bean" type="Tcomponent" minOccurs="0"
                    maxOccurs="1"/>
                <xsd:any namespace="##other" minOccurs="0" maxOccurs="unbounded"
                    processContents="lax"/>
                <xsd:attribute name="interface" type="Tclass" use="optional"/>
                <xsd:attribute name="ref" type="Tidref" use="optional"/>
                <xsd:attribute name="depends-on" type="xsd:normalizedString" use="optional"/>
                <xsd:attribute name="auto-export" type="TautoExportModes" default="disabled"/>
                <xsd:attribute name="ranking" type="xsd:int" default="0"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="TregistrationListener">
        <xsd:group ref="refOrTargetComponent"/>
        <xsd:attribute name="ref" type="Tidref"
            use="optional"/>
        <!--  ### why are there both required? -->
        <xsd:attribute name="registration-method"
            type="Tmethod" use="required"/>
        <xsd:attribute name="unregistration-method"
            type="Tmethod" use="required"/>
    </xsd:complexType>

	<!--
	Values
	-->

	<xsd:group name="value">
        <xsd:choice minOccurs="0" maxOccurs="1">
			<xsd:group ref="nonNullValue"/>
            <xsd:element name="null" type="Tnull"/>
		</xsd:choice>
	</xsd:group>

    <xsd:complexType name="Tnull"/>

	<xsd:group name="nonNullValue">
        <xsd:choice minOccurs="0" maxOccurs="1">
			<xsd:group ref="allComponents"/>
			<xsd:choice minOccurs="0" maxOccurs="1">
				<xsd:element name="ref" type="Tref"/>
				<xsd:element name="idref" type="Tref"/>
				<xsd:element name="value" type="Tvalue"/>
				<xsd:element name="list" type="Tcollection"/>
				<xsd:element name="set" type="Tcollection"/>
				<xsd:element name="map" type="Tmap"/>
				<xsd:element name="array" type="Tcollection"/>
				<xsd:element name="props" type="Tprops"/>
				<xsd:any namespace="##other" processContents="strict" minOccurs="0"
					maxOccurs="unbounded"/>
			</xsd:choice>
        </xsd:choice>
	</xsd:group>

	<xsd:complexType name="Tref">
		<xsd:complexContent>
			<!--- ### what is this restriction doing ??? -->
			<xsd:restriction base="xsd:anyType">
				<xsd:attribute name="component" type="Tidref" use="required"/>
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Tvalue" mixed="true">
		<!-- #### why should arbitrary elements be allowed in a <value>?-->
        <xsd:any minOccurs="0" maxOccurs="unbounded"/>
		<xsd:attribute name="type" type="Tclass"/>
	</xsd:complexType>

	<!-- Collection Values -->

	<xsd:complexType name="Tcollection">
		<xsd:complexContent>
			<xsd:extension base="TtypedCollection">
				<xsd:group ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Tprops">
   		<xsd:element name="prop" type="Tprop" maxOccurs="unbounded"/>
	</xsd:complexType>

    <xsd:complexType name="Tprop" mixed=true">
        <xsd:attribute name="key" type="TstringValue"
            use="required"/>
        <xsd:attribute name="value" type="TstringValue"
            use="optional"/>
    </xsd:complexType>

    <!-- 'map' element type -->
    <xsd:complexType name="Tmap">
        <xsd:complexContent>
            <xsd:extension base="TtypedCollection">
                <xsd:element name="entry" type="Tentry" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:attribute name="key-type" type="xsd:string"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <!-- 'entry' element type -->
    <xsd:complexType name="Tentry">
        <xsd:sequence>
            <xsd:element name="key" type="Tkey" minOccurs="0"/>
            <xsd:group ref="value"/>
        </xsd:sequence>
        <xsd:attribute name="key" type="TstringValue"/>
        <xsd:attribute name="key-ref" type="Tidref"/>
        <xsd:attribute name="value" type="TstringValue"/>
        <xsd:attribute name="value-ref" type="Tidref"/>
    </xsd:complexType>

	<xsd:complexType name="TtypedCollection">
		<xsd:complexContent>
            <xsd:attribute name="value-type" type="Tclass"/>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- General types -->

	<xsd:complexType name="Tdescription" mixed="true">
		<xsd:choice minOccurs="0" maxOccurs="unbounded"/>
	</xsd:complexType>

	<xsd:complexType name="Tinterfaces">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="value" type="Tclass"/>
		</xsd:choice>
	</xsd:complexType>

	<!-- Should be used for all attributes and elements that refer to classes -->
	<xsd:simpleType name="Tclass">
		<xsd:restriction base="xsd:NCName"/>
	</xsd:simpleType>

	<!-- Should be used for all attributes and elements that refer to method names -->
	<xsd:simpleType name="Tmethod">
		<xsd:restriction base="xsd:NCName"/>
	</xsd:simpleType>

	<!-- Should be used for all attributes and elements that refer to method names -->
	<xsd:simpleType name="Tidref">
		<xsd:restriction base="xsd:NCName"/>
	</xsd:simpleType>

	<!-- Should be used for value= attributes that specify string values -->
	<xsd:simpleType name="TstringValue">
		<xsd:restriction base="xsd:normalizedString"/>
	</xsd:simpleType>

</xsd:schema>

=== Amit2016-17/osgi/org.osgi.test.cases.blueprint/src/org/osgi/test/cases/blueprint/components/serviceimport/ref_list_reference_comparator_reference.xml
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

    <description>
        This is a checker for different sorting combinations.
    </description>

    <!-- This is the same, but using a comparator that sorts on ServiceReferences -->
    <bean id="ServiceReferenceComparatorChecker" class="org.osgi.test.cases.blueprint.components.serviceimport.ReferenceCollectionSortChecker" init-method="init">
        <argument value="ServiceReferenceComparatorChecker"/>
        <property name="serviceManager">
            <reference interface="org.osgi.test.cases.blueprint.services.ServiceManager"/>
        </property>
        <property name="bundleContext" ref="bundleContext"/>
        <property name="useReferences" value="true"/>
        <property name="list">
            <ref-list interface="org.osgi.test.cases.blueprint.services.TestServiceOne" ordering-basis="service-reference" member-type="service-reference">
                <comparator>
                    <bean class="org.osgi.test.cases.blueprint.components.serviceimport.ServiceReferenceComparator"/>
                </comparator>
            </ref-list>
        </property>
        <property name="sortOrder">
            <list>
                <value>ServiceOneA</value>
                <value>ServiceOneB</value>
                <value>ServiceOneC</value>
                <value>ServiceOneD</value>
                <value>TestServiceF</value>
            </list>
        </property>
    </bean>
</blueprint>

=== Amit2016-17/osgi/org.osgi.test.cases.blueprint/src/org/osgi/test/cases/blueprint/components/serviceimport/Service_reference_null_injection.xml
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

    <description>
        This is a test for ServiceReference injection with optional availability.  This should inject a null
        value for the reference.
    </description>

    <!-- single shared instance of the imported service -->
    <reference id="ServiceOne" interface="org.osgi.test.cases.blueprint.services.TestServiceOne" availability="optional"/>

   <!-- We pull in the bundle, the bundle context, as well as the service reference -->
   <bean id="ServiceReferenceChecker" class="org.osgi.test.cases.blueprint.components.serviceimport.NullServiceReferenceInjection">
       <argument value="ServiceReferenceChecker"/>
       <argument ref="bundleContext"/>
       <argument ref="bundle"/>
       <property name="reference" ref="ServiceOne"/>
   </bean>
</blueprint>

=== Amit2016-17/osgi/org.osgi.test.cases.blueprint/src/org/osgi/test/cases/blueprint/components/injection/classtype_factory_property_injection.xml
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

<!-- instance factory -->
    <bean id="compFactory" class="org.osgi.test.cases.blueprint.components.injection.PropertyInjectionInstanceFactory">
		<!-- collaborators and configuration for this component go here -->
    </bean>


<!-- URL: 3 cases -->
	<bean id="compURL" factory-method="makeInstance" factory-component="compFactory">
		<property name="url" value="http://www.osgi.org"/>
	</bean>

    <bean id="compURLNull" factory-method="makeInstance" factory-component="compFactory">
		<property name="url"><null/></property>
	</bean>

	<bean id="compURL_EleValue" factory-method="makeInstance" factory-component="compFactory">
		<property name="url"><value>http://www.osgi.org</value></property>
	</bean>

<!-- Date: 5 cases -->
<!-- TODO Temporarily disabled...bugzilla 1145
	<bean id="compDate" factory-method="makeInstance" factory-component="compFactory">
		<property name="date" value="6/1/1999"/>
	</bean>

    <bean id="compDate2" factory-method="makeInstance" factory-component="compFactory">
		<property name="date" value="2000-12-31 23:59:59"/>
	</bean>

    <bean id="compDate3" factory-method="makeInstance" factory-component="compFactory">
		<property name="date" value="January 1, 1970, 00:00:00 GMT"/>
	</bean>

    <bean id="compDateNull" factory-method="makeInstance" factory-component="compFactory">
		<property name="date"><null/></property>
	</bean>

	<bean id="compDate_EleValue" factory-method="makeInstance" factory-component="compFactory">
		<property name="date"><value type="java.util.Date">1970-1-1</value></property>
	</bean>
    -->

<!-- Locale:5 cases -->
	<bean id="compLocale" factory-method="makeInstance" factory-component="compFactory">
		<property name="locale" value="en"/>
	</bean>

	<bean id="compLocale2" factory-method="makeInstance" factory-component="compFactory">
		<property name="locale" value="zh_CN"/>
	</bean>

	<bean id="compLocale3" factory-method="makeInstance" factory-component="compFactory">
		<property name="locale" value="en_US_WIN"/>
	</bean>

    <bean id="compLocaleNull" factory-method="makeInstance" factory-component="compFactory">
		<property name="locale"><null/></property>
	</bean>

	<bean id="compLocale_EleValue" factory-method="makeInstance" factory-component="compFactory">
		<property name="locale"><value>en_US</value></property>
	</bean>

<!-- Class:3 cases -->
	<bean id="compClass" factory-method="makeInstance" factory-component="compFactory">
		<property name="class" value="java.lang.String"/>
	</bean>

    <bean id="compClassNull" factory-method="makeInstance" factory-component="compFactory">
		<property name="class"><null/></property>
	</bean>

	<bean id="compClass_EleValue" factory-method="makeInstance" factory-component="compFactory">
		<property name="class"><value>org.osgi.test.cases.blueprint.components.injection.PropertyInjection</value></property>
	</bean>

<!-- Properties: 4 cases -->
	<bean id="compProperties" factory-method="makeInstance" factory-component="compFactory">
		<property name="properties" value="Name=Rex"/>
	</bean>

	<bean id="compProperties_EleValue" factory-method="makeInstance" factory-component="compFactory">
		<property name="properties">
			<value>
				Name= Rex
				Organization =OSGi Alliance
				Nationality    :    China
				Language: \u4e2d\u6587, English
				Graduated=Shanghai Jiao Tong University
				#key is the word before the first whitespace - "Major"
				Major Computer Science

				!Gender should be a String ""
				Gender

			</value>
		</property>
	</bean>

	<bean id="compPropertiesEmpty" factory-method="makeInstance" factory-component="compFactory">
		<property name="properties"><value>  </value></property>
	</bean>

    <bean id="compPropertiesNull" factory-method="makeInstance" factory-component="compFactory">
		<property name="properties"><null/></property>
	</bean>




</blueprint>
