=== Amit2016-17/osgi/org.osgi.test.cases.zigbee/zcl.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:simpleType name="ProfileID" id="ProfileID">
    <xs:union memberTypes="xs:unsignedShort">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{4}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="ManufacturerCode" id="ManufacturerCode">
    <xs:union memberTypes="xs:unsignedInt">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{4}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="ClusterID">
    <xs:union memberTypes="xs:unsignedShort">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{4}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>


  <xs:simpleType name="AttributeID">
    <xs:union memberTypes="xs:unsignedShort">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{4}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>


  <xs:simpleType name="CommandID">
    <xs:union memberTypes="xs:unsignedByte">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{2}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>


  <xs:simpleType name="HexString" id="HexString">
    <xs:restriction base="xs:token">
      <xs:pattern value="[0-9a-fA-F]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="param">
    <xs:complexType>
      <xs:attribute name="name" type="xs:NCName" />
      <xs:attribute name="dataType" type="xs:NCName" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="command">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="param" />
      </xs:sequence>
      <xs:attribute name="id" use="required" type="CommandID" />
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="mandatory" type="xs:boolean" default="true" />
      <xs:attribute name="responseId" type="CommandID" />
      <xs:attribute name="zclFrame" type="HexString" />
      <xs:attribute name="isClusterSpecificCommand" type="xs:boolean" default="true" />

    </xs:complexType>
  </xs:element>

  <xs:element name="attribute">
    <xs:annotation>
      <xs:documentation>
        For dataTypes see org.osgi.service.zigbee.types the test needs at least one attribute which is read only.
        At
        least one attribute must have a boolean dataType to test INVALID_DATATYPE exception.
        At least one attribute must be
        reportable for eventing test purpose.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="id" type="AttributeID" use="required" />
          <xs:attribute name="readOnly" type="xs:boolean" use="required" />
          <xs:attribute name="name" type="xs:string" use="required" />
          <xs:attribute name="reportable" type="xs:boolean" use="required" />
          <xs:attribute name="dataType" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="client">
    <xs:annotation>
      <xs:documentation>
        The 'client' element collects all the cluster server-side attributes and all the commands consumed by the
        client side of a cluster.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="command" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="server">
    <xs:annotation>
      <xs:documentation>
        The 'server' element collects all the cluster server-side attributes and all the commands consumed by the
        server side of a cluster.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="command" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="cluster">
    <xs:annotation>
      <xs:documentation>
        Defines a specific cluster in terms of client and server attributes and commands.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="server" minOccurs="0" maxOccurs="1" />
        <xs:element ref="client" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="required" />
      <xs:attribute type="ClusterID" name="id" use="required" />
      <xs:attribute type="xs:string" name="domain" />
    </xs:complexType>
  </xs:element>

  <xs:element name="clusters">
    <xs:annotation>
      <xs:documentation>
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cluster" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="profile">
    <xs:annotation>
      <xs:documentation>
        Defines a ZCL profile.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clusters" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="required" />
      <xs:attribute type="ProfileID" name="profileId" use="required" />
    </xs:complexType>
  </xs:element>


  <xs:element name="profiles">
    <xs:annotation>
      <xs:documentation>
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="profile" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Amit2016-17/osgi/org.osgi.test.cases.zigbee/zcl.xml
<?xml version="1.0" encoding="utf-8" ?>
<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zcl.xsd">
  <profile profileId="7" name="profileName">
    <clusters>
      <cluster id="3" name="light cluster">
        
        <server>
          <attribute id="8" name="version" reportable="false" readOnly="true" dataType="ZigBeeUnsignedInteger16" />
          <attribute id="6" name="unknown" reportable="true" readOnly="false" dataType="ZigBeeBoolean" />
          <command id="3" name="commandName" responseId="7">
            <param dataType="ZigBeeBoolean" />
          </command>
        </server>
        
        <client>
          <command id="7" name="commandName1">
            <param dataType="ZigBeeBoolean" />
          </command>
        </client>
      </cluster>
    </clusters>
  </profile>
</profiles>
